version: "3"
services:
    tenderapplicationbackend:
        build: .
        container_name: tenderback
        ports:
            - "8000:80"
        depends_on:
            - db
        links:
            - db:db
    db:
        image: "microsoft/mssql-server-linux"
        container_name: sqlserver
        environment:
            SA_PASSWORD: "VerySecurePassword_1"
            ACCEPT_EULA: "Y"
        ports: 
            - "1433:1433"